name: 'Build and release'

on:
  push:
    tags:
      - '1.*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install composer dependencies
        run: composer update --no-dev --prefer-dist

      - name: Build artifact
        run: make build

      - id: release_info
        uses: toolmantim/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create ZIP
        run: zip -r apirone-v${{ github.ref_name }}.zip ./apirone

      - name: Output some vars
        run: echo ${{ github }}

      - name: Publish to GitHub Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release_info.outputs.upload_url }}
          # asset_path: ./${{ github.event.repository.name }}/${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
          # asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
          # asset_path: apirone-v${{ github.event.release.tag_name }}.zip
          # asset_name: apirone-v${{ github.event.release.tag_name }}.zip
          asset_path: apirone-v${{ github.ref_name }}.zip
          asset_name: apirone-v${{ github.ref_name }}.zip
          asset_content_type: application/zip
      # - name: Release
      #   id: release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: |
      #       apirone-v${{ github.event.release.tag_name }}.zip
      


        
  
